apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-deployment-non-resilent
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: isilon
