#use the default driver settings from csi-driver not the storage class
#no pvc or pv
apiVersion: v1
kind: Pod
metadata:
  name: my-csi-app-inline-volume
spec:
  containers:
     - name: my-frontend
       image: busybox
       command: [ "sleep", "100000" ]
       volumeMounts:
       - mountPath: "/data"
         name: my-csi-volume
  volumes:
    - name: my-csi-volume
       csi:
        driver: csi-isilon.dellemc.com
        volumeAttributes:
        size: "2Gi"
        ClusterName: "ps1"
