apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set-ngnix
spec:
  serviceName: nginx
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 101
        runAsGroup: 101
        runAsNonRoot: true
        runAsUser: 101
      containers:
        - name: nginx
          image: gcr.io/devcon-anthos/nginxinc/nginx-unprivileged:1.20
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: stateful-set-ngnix-pvc
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: stateful-set-ngnix-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: isilon
        resources:
          requests:
            storage: 10Gi